blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://mher.club/discord
    about: Our support Discord, if you are unsure or you have a question please do not hesitate to seek help.
